name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: ${{ matrix.platform }} / Swift ${{ matrix.swift }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [macos]
        swift: ["6.0"]
        include:
          - platform: macos
            os: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Not working https://github.com/swift-actions/setup-swift/issues/739
      # - name: Set up Swift ${{ matrix.swift }}
      #   if: matrix.platform != 'ios'
      #   uses: swift-actions/setup-swift@v2
      #   with:
      #     swift-version: ${{ matrix.swift }}

      - name: Cache SwiftPM (Linux/macOS)
        if: matrix.platform == 'linux' || matrix.platform == 'macos'
        uses: actions/cache@v4
        with:
          path: |
            .build
            ~/.swiftpm
            ~/.cache/org.swift.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-swiftpm-${{ matrix.swift }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-${{ matrix.swift }}-
            ${{ runner.os }}-swiftpm-

      - name: Swift version
        run: swift --version

      - name: Build (Linux/macOS)
        if: matrix.platform != 'ios'
        run: swift build -v

      - name: Test (Linux/macOS)
        if: matrix.platform != 'ios'
        run: swift test -v
